// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhhY_WKdzTzBJUpglxplOlpVeUdZRsE08',
    appId: '1:486916365224:web:123b98287ca5f6ddeedb9d',
    messagingSenderId: '486916365224',
    projectId: 'hwiapp',
    authDomain: 'hwiapp.firebaseapp.com',
    storageBucket: 'hwiapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFUTDWl9JaQOKwDP3ivEayxkd29otwNgk',
    appId: '1:486916365224:android:9cbd470d19493f3aeedb9d',
    messagingSenderId: '486916365224',
    projectId: 'hwiapp',
    storageBucket: 'hwiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9RquhLPTTGQVOBEcDkbKh35FkD4mVqE',
    appId: '1:486916365224:ios:2f824cef96559897eedb9d',
    messagingSenderId: '486916365224',
    projectId: 'hwiapp',
    storageBucket: 'hwiapp.appspot.com',
    iosClientId: '486916365224-2gokeghhp0jjtvj6c3pf7qge4e3humah.apps.googleusercontent.com',
    iosBundleId: 'com.example.hlgAppZepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG9RquhLPTTGQVOBEcDkbKh35FkD4mVqE',
    appId: '1:486916365224:ios:9800a1558b7bdaa2eedb9d',
    messagingSenderId: '486916365224',
    projectId: 'hwiapp',
    storageBucket: 'hwiapp.appspot.com',
    iosClientId: '486916365224-bealp8g07bdl83noekas0bg35mp03vbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.hlgAppZepro.RunnerTests',
  );
}
